# ...[rest of workflow above unchanged]...

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create .streamlit config.toml
      run: |
        mkdir -p ~/.streamlit/
        echo "\
        [server]\n\
        port=\${PORT}\n\
        enableCORS=false\n\
        headless=true\n\
        " > ~/.streamlit/config.toml

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # ...[rest of steps unchanged]...
